name: "snyk container"
on: [push, pull_request]
jobs:
  SNYK:
    runs-on: ubuntu-latest    
    steps:
      - name: Download Snyk
      - uses: snyk/actions/setup@master
        id: snyk
        
      - name: Container test
        id: container
        continue-on-error: true
        run: | 
          set +e
          docker login  trialkxioiz.jfrog.io/snyktest-docker-local -u dakshita.joshi@esecforte.com -p cmVmdGtuOjAxOjE3ODQ3MTYyNTI6UktDQWZ1N0JhZ3ZmMnFqakRDTGRtVEluSnlk
          docker pull debian:dj-slim
          snyk container test debian:dj-slim --severity-threshold=critical
          echo "RESULT=$?" >> $GITHUB_OUTPUT
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}         
          
      - name: Fail Test
        run: | 
          if [ ${{ steps.container.outputs.RESULT }} == 1 ]; then
          echo "container test failed - send report to team"

