name: "snyk container"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull debian:sid-slim
        
      - name: Container
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: container test debian:sid-slim
          
      - name: check
        run: ls
