name: "snyk container"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: snyk/actions/setup@master
        id: snyk
        
      - name: Pull image
        run: docker pull debian:sid-slim
        
#      - name: Container Test
 #       continue-on-error: true
 #       run: | 
 #         set +e
 #         snyk container test debian:sid-slim
 #         exitcode="$?"
 #         echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
 #         exit "$exitcode"
 #       env:
 #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Container
        id: container
        continue-on-error: true
        run: | 
          set +e
          snyk container test debian:sid-slim
          RESULT="$?"
          echo "$RESULT" >> $GITHUB_OUTPUT
 #         exit $RESULT
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}         
          
      - name: ECHO
        run: | 
          echo "$RESULT"
          echo "$GITHUB_OUTPUT"
          echo "${{ steps.container.outputs.RESULT }]"
          
      - name: Container Monitor
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: container monitor debian:sid-slim
