name: "snyk container"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: snyk/actions/setup@master
        id: snyk
      - name: Pull image
        run: docker pull debian:sid-slim
        
      - name: Container Test
        run: snyk container test debian:sid-slim
                 
      - name: Container Monitor
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: container monitor debian:sid-slim

