name: "snyk container"
on: [push, pull_request]
jobs:
  SNYK:
    runs-on: ubuntu-latest    
    steps:
      - uses: snyk/actions/setup@master
        id: snyk

      - uses: docker/login-action@v3.4.0
        id: docker
        with:
          registry: trialkxioiz.jfrog.io/snyktest-docker-local
          username: dakshita.joshi@esecforte.com
          password: cmVmdGtuOjAxOjE3ODQ3MTYyNTI6UktDQWZ1N0JhZ3ZmMnFqakRDTGRtVEluSnlk
              
      - name: Container test
        id: container
        continue-on-error: true
        run: | 
          set +e
          docker pull trialkxioiz.jfrog.io/snyktest-docker-local/debian:dj-slim
          snyk container test trialkxioiz.jfrog.io/snyktest-docker-local/debian:dj-slim --severity-threshold=critical
          echo "RESULT=$?" >> $GITHUB_OUTPUT
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}         
          
      - name: Fail Test
        continue-on-error: true
        run: | 
          if [ ${{ steps.container.outputs.RESULT }} == 1 ]; then
          echo "container test failed - send report to team"
          fi

