name: import sync

on:
  push:
    branches: [ main ]

jobs:
  sync-import:
    runs-on: ubuntu-latest
    name: download api import
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:

    - name: Download Snyk Import
      run: |
         wget -O snyk-api-import https://github.com/snyk/snyk-api-import/releases/download/v2.21.6/snyk-api-import-linux
         chmod a+x ./snyk
         ls
    - name: Run Snyk Import
      run: |
         DEBUG=snyk* snyk-api-import import --file=targets.json
